channels:
    - conda-forge
    - defaults
dependencies:
    - matplotlib
    - mdanalysis
    - mdanalysistests
    - mdtraj
    - jupyterlab=1.0.9
    - nodejs
    - ipython
    - ipywidgets=7.5.1
    - notebook
    - ipykernel
    - nglview=2.7
    - rdkit::rdkit
    - pip:
        - pytraj
        - ipython_blocking
        - moviepy
